Traceback (most recent call last):
  File "C:\Users\User\anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\User\anaconda3\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\User\anaconda3\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\User\anaconda3\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\User\anaconda3\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\User\anaconda3\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\User\anaconda3\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\User\anaconda3\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# model = "T4~(female+black+othrace+C(dep)+q2+q3+q4+q5+q6+agelt35+agegt54+durable+lusd+husd)**2"
model_results = sm.OLS( y, X_vars ).fit().get_robustcov_results(cov_type = "HC1")

print(model_results.summary())
print( "Number of regressors in the basic model:",len(model_results.params), '\n')
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mValueError[0m                                Traceback (most recent call last)
Input [1;32mIn [9][0m, in [0;36m<cell line: 2>[1;34m()[0m
[0;32m      1[0m [38;5;66;03m# model = "T4~(female+black+othrace+C(dep)+q2+q3+q4+q5+q6+agelt35+agegt54+durable+lusd+husd)**2"[39;00m
[1;32m----> 2[0m model_results [38;5;241m=[39m [43msm[49m[38;5;241;43m.[39;49m[43mOLS[49m[43m([49m[43m [49m[43my[49m[43m,[49m[43m [49m[43mX_vars[49m[43m [49m[43m)[49m[38;5;241m.[39mfit()[38;5;241m.[39mget_robustcov_results(cov_type [38;5;241m=[39m [38;5;124m"[39m[38;5;124mHC1[39m[38;5;124m"[39m)
[0;32m      4[0m [38;5;28mprint[39m(model_results[38;5;241m.[39msummary())
[0;32m      5[0m [38;5;28mprint[39m( [38;5;124m"[39m[38;5;124mNumber of regressors in the basic model:[39m[38;5;124m"[39m,[38;5;28mlen[39m(model_results[38;5;241m.[39mparams), [38;5;124m'[39m[38;5;130;01m\n[39;00m[38;5;124m'[39m)

File [1;32m~\anaconda3\lib\site-packages\statsmodels\regression\linear_model.py:890[0m, in [0;36mOLS.__init__[1;34m(self, endog, exog, missing, hasconst, **kwargs)[0m
[0;32m    887[0m     msg [38;5;241m=[39m ([38;5;124m"[39m[38;5;124mWeights are not supported in OLS and will be ignored[39m[38;5;124m"[39m
[0;32m    888[0m            [38;5;124m"[39m[38;5;124mAn exception will be raised in the next version.[39m[38;5;124m"[39m)
[0;32m    889[0m     warnings[38;5;241m.[39mwarn(msg, ValueWarning)
[1;32m--> 890[0m [38;5;28msuper[39m(OLS, [38;5;28mself[39m)[38;5;241m.[39m[38;5;21m__init__[39m(endog, exog, missing[38;5;241m=[39mmissing,
[0;32m    891[0m                           hasconst[38;5;241m=[39mhasconst, [38;5;241m*[39m[38;5;241m*[39mkwargs)
[0;32m    892[0m [38;5;28;01mif[39;00m [38;5;124m"[39m[38;5;124mweights[39m[38;5;124m"[39m [38;5;129;01min[39;00m [38;5;28mself[39m[38;5;241m.[39m_init_keys:
[0;32m    893[0m     [38;5;28mself[39m[38;5;241m.[39m_init_keys[38;5;241m.[39mremove([38;5;124m"[39m[38;5;124mweights[39m[38;5;124m"[39m)

File [1;32m~\anaconda3\lib\site-packages\statsmodels\regression\linear_model.py:717[0m, in [0;36mWLS.__init__[1;34m(self, endog, exog, weights, missing, hasconst, **kwargs)[0m
[0;32m    715[0m [38;5;28;01melse[39;00m:
[0;32m    716[0m     weights [38;5;241m=[39m weights[38;5;241m.[39msqueeze()
[1;32m--> 717[0m [38;5;28msuper[39m(WLS, [38;5;28mself[39m)[38;5;241m.[39m[38;5;21m__init__[39m(endog, exog, missing[38;5;241m=[39mmissing,
[0;32m    718[0m                           weights[38;5;241m=[39mweights, hasconst[38;5;241m=[39mhasconst, [38;5;241m*[39m[38;5;241m*[39mkwargs)
[0;32m    719[0m nobs [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mexog[38;5;241m.[39mshape[[38;5;241m0[39m]
[0;32m    720[0m weights [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mweights

File [1;32m~\anaconda3\lib\site-packages\statsmodels\regression\linear_model.py:191[0m, in [0;36mRegressionModel.__init__[1;34m(self, endog, exog, **kwargs)[0m
[0;32m    190[0m [38;5;28;01mdef[39;00m [38;5;21m__init__[39m([38;5;28mself[39m, endog, exog, [38;5;241m*[39m[38;5;241m*[39mkwargs):
[1;32m--> 191[0m     [38;5;28msuper[39m(RegressionModel, [38;5;28mself[39m)[38;5;241m.[39m[38;5;21m__init__[39m(endog, exog, [38;5;241m*[39m[38;5;241m*[39mkwargs)
[0;32m    192[0m     [38;5;28mself[39m[38;5;241m.[39m_data_attr[38;5;241m.[39mextend([[38;5;124m'[39m[38;5;124mpinv_wexog[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mwendog[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mwexog[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mweights[39m[38;5;124m'[39m])

File [1;32m~\anaconda3\lib\site-packages\statsmodels\base\model.py:267[0m, in [0;36mLikelihoodModel.__init__[1;34m(self, endog, exog, **kwargs)[0m
[0;32m    266[0m [38;5;28;01mdef[39;00m [38;5;21m__init__[39m([38;5;28mself[39m, endog, exog[38;5;241m=[39m[38;5;28;01mNone[39;00m, [38;5;241m*[39m[38;5;241m*[39mkwargs):
[1;32m--> 267[0m     [38;5;28msuper[39m()[38;5;241m.[39m[38;5;21m__init__[39m(endog, exog, [38;5;241m*[39m[38;5;241m*[39mkwargs)
[0;32m    268[0m     [38;5;28mself[39m[38;5;241m.[39minitialize()

File [1;32m~\anaconda3\lib\site-packages\statsmodels\base\model.py:92[0m, in [0;36mModel.__init__[1;34m(self, endog, exog, **kwargs)[0m
[0;32m     90[0m missing [38;5;241m=[39m kwargs[38;5;241m.[39mpop([38;5;124m'[39m[38;5;124mmissing[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mnone[39m[38;5;124m'[39m)
[0;32m     91[0m hasconst [38;5;241m=[39m kwargs[38;5;241m.[39mpop([38;5;124m'[39m[38;5;124mhasconst[39m[38;5;124m'[39m, [38;5;28;01mNone[39;00m)
[1;32m---> 92[0m [38;5;28mself[39m[38;5;241m.[39mdata [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39m_handle_data(endog, exog, missing, hasconst,
[0;32m     93[0m                               [38;5;241m*[39m[38;5;241m*[39mkwargs)
[0;32m     94[0m [38;5;28mself[39m[38;5;241m.[39mk_constant [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mdata[38;5;241m.[39mk_constant
[0;32m     95[0m [38;5;28mself[39m[38;5;241m.[39mexog [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mdata[38;5;241m.[39mexog

File [1;32m~\anaconda3\lib\site-packages\statsmodels\base\model.py:132[0m, in [0;36mModel._handle_data[1;34m(self, endog, exog, missing, hasconst, **kwargs)[0m
[0;32m    131[0m [38;5;28;01mdef[39;00m [38;5;21m_handle_data[39m([38;5;28mself[39m, endog, exog, missing, hasconst, [38;5;241m*[39m[38;5;241m*[39mkwargs):
[1;32m--> 132[0m     data [38;5;241m=[39m handle_data(endog, exog, missing, hasconst, [38;5;241m*[39m[38;5;241m*[39mkwargs)
[0;32m    133[0m     [38;5;66;03m# kwargs arrays could have changed, easier to just attach here[39;00m
[0;32m    134[0m     [38;5;28;01mfor[39;00m key [38;5;129;01min[39;00m kwargs:

File [1;32m~\anaconda3\lib\site-packages\statsmodels\base\data.py:673[0m, in [0;36mhandle_data[1;34m(endog, exog, missing, hasconst, **kwargs)[0m
[0;32m    670[0m     exog [38;5;241m=[39m np[38;5;241m.[39masarray(exog)
[0;32m    672[0m klass [38;5;241m=[39m handle_data_class_factory(endog, exog)
[1;32m--> 673[0m [38;5;28;01mreturn[39;00m klass(endog, exog[38;5;241m=[39mexog, missing[38;5;241m=[39mmissing, hasconst[38;5;241m=[39mhasconst,
[0;32m    674[0m              [38;5;241m*[39m[38;5;241m*[39mkwargs)

File [1;32m~\anaconda3\lib\site-packages\statsmodels\base\data.py:87[0m, in [0;36mModelData.__init__[1;34m(self, endog, exog, missing, hasconst, **kwargs)[0m
[0;32m     85[0m [38;5;28mself[39m[38;5;241m.[39mk_constant [38;5;241m=[39m [38;5;241m0[39m
[0;32m     86[0m [38;5;28mself[39m[38;5;241m.[39m_handle_constant(hasconst)
[1;32m---> 87[0m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_check_integrity[49m[43m([49m[43m)[49m
[0;32m     88[0m [38;5;28mself[39m[38;5;241m.[39m_cache [38;5;241m=[39m {}

File [1;32m~\anaconda3\lib\site-packages\statsmodels\base\data.py:531[0m, in [0;36mPandasData._check_integrity[1;34m(self)[0m
[0;32m    527[0m [38;5;66;03m# exog can be None and we could be upcasting one or the other[39;00m
[0;32m    528[0m [38;5;28;01mif[39;00m (exog [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m [38;5;129;01mand[39;00m
[0;32m    529[0m         ([38;5;28mhasattr[39m(endog, [38;5;124m'[39m[38;5;124mindex[39m[38;5;124m'[39m) [38;5;129;01mand[39;00m [38;5;28mhasattr[39m(exog, [38;5;124m'[39m[38;5;124mindex[39m[38;5;124m'[39m)) [38;5;129;01mand[39;00m
[0;32m    530[0m         [38;5;129;01mnot[39;00m [38;5;28mself[39m[38;5;241m.[39morig_endog[38;5;241m.[39mindex[38;5;241m.[39mequals([38;5;28mself[39m[38;5;241m.[39morig_exog[38;5;241m.[39mindex)):
[1;32m--> 531[0m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m([38;5;124m"[39m[38;5;124mThe indices for endog and exog are not aligned[39m[38;5;124m"[39m)
[0;32m    532[0m [38;5;28msuper[39m(PandasData, [38;5;28mself[39m)[38;5;241m.[39m_check_integrity()

[1;31mValueError[0m: The indices for endog and exog are not aligned
ValueError: The indices for endog and exog are not aligned

